auto: true

#markdown: rdiscount
highlighter: 'rouge'
#paginate: 8
permalink: /:title

title: SugelaBoy
url: http://crazyounger.github.io
feed: /atom.xml
author_info: <a href="http://crazyounger.github.io/">SugulaBoy</a>
